swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /sample_spa/v1

# Paths supported by the server application
paths:
  /student:
    get:
      operationId: app.student.read_all
      tags:
        - student
      summary: Read the entire list of student
      description: Read the list of student
      parameters:
        - name: count
          in: query
          type: integer
          description: Number of student to get from student
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start retrieving student list
          required: false
      responses:
        200:
          description: Successfully read student list operation
          schema:
            type: array
            items:
              properties:
                usn:
                  type: integer
                fname:
                  type: string
                lname:
                  type: string
                gpa:
                  type: number
                  multipleOf: 0.01
                email:
                  type: string
                phone_no:
                  type: number

    post:
      operationId: app.student.create
      tags:
        - student
      summary: Create a student and add it to the student list
      description: Create a new student in the student list
      parameters:
        - name: student
          in: body
          description: student to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of student to create
              lname:
                type: string
                description: Last name of student to create
              gpa:
                type: number
                multipleOf: 0.01
              email:
                type: string
              pno:
                type: number
      responses:
        201:
          description: Successfully created student in list

  /student/{usn}:
    get:
      operationId: app.student.read_one
      tags:
        - student
      summary: Read one student from the student list
      description: Read one student from the student list
      parameters:
        - name: usn
          in: path
          description: Last name of the student to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read student from student list operation
          schema:
            properties:
              usn:
                type: integer
              fname:
                type: string
              lname:
                type: string
              gpa:
                  type: number
                  multipleOf: 0.01
              email:
                type: string
              phone_no:
                type: number

    put:
      operationId: app.student.update
      tags:
        - student
      summary: Update a student in the student list
      description: Update a student in the student list
      parameters:
        - name: usn
          in: path
          description: Last name of the student to update in the list
          type: integer
          required: True
        - name: student
          in: body
          schema:
            type: object
            properties:
              usn:
                type: integer
              fname:
                type: string
              lname:
                type: string
              gpa:
                  type: number
                  multipleOf: 0.01
              email:
                type: string
              phone_no:
                type: number
      responses:
        200:
          description: Successfully updated student in student list

    delete:
      operationId: app.student.delete
      tags:
        - student
      summary: Delete a student from the student list
      description: Delete a student
      parameters:
        - name: usn
          in: path
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted a student from student list